#!/usr/bin/env python3
import os
title = input("the title of new post is:")
words = title.replace("?", "").replace("!", "").strip().split()
post = "-".join(words) + ".md"
if os.path.exists("_posts") == False:
    print("can't not find main folder: _posts, then creat new")
    os.mkdir("_posts")
else:
    path = os.path.join("_posts", post)
    with open(path, 'w') as fh:
        print(f"## {title}", file=fh)
